# Generated by Django 5.0.6 on 2024-06-29 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interests', models.TextField(blank=True, help_text='Your interests and hobbies.')),
                ('goals', models.TextField(blank=True, help_text='Your mental wellness goals.')),
                ('communication_styles', models.CharField(choices=[('Email', 'Email'), ('Phone', 'Phone'), ('Chat', 'Chat')], default='Email', help_text='Preferred method of communication.', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
